-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(zpipe)
TARGET=$(BIN_DIRECTORY)zpipe
-include $(ROOT_PROJECT_DIRECTORY)src/executable.mk
