-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(dumpbrain)
TARGET=$(BIN_DIRECTORY)dumpbrain
-include $(ROOT_PROJECT_DIRECTORY)src/executable.mk
